name: Ecom Workflow

on:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      client_changed: ${{steps.client_changed.client}}
      server_changed: ${{steps.server_changed.backend}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show changed files
        run: git diff --name-only ${{ github.event.before }} ${{ github.sha }}
      # - name: Check for changes in client
      #   id: client_changed
      #   uses: dorny/paths-filter@v3
      #   with:
      #     filters: |
      #       client:
      #         - "client/**"

      - name: Check for changes in server
        id: server_changed
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'backend/**/*'

      - name: Debug filter outputs
        run: |
          echo "Backend: ${{ steps.server_changed.outputs.backend }}"

  # client:
  #   needs: check-changes
  #   runs-on: ubuntu-latest
  #   if: needs.check-changes.outputs.client_changed == 'true'
  #   steps:
  #     - name: Nice working
  #       run: echo "Client Changes Detected"

  backend:
    needs: check-changes
    runs-on: ubuntu-latest
    # if: needs.check-changes.outputs.server_changed == 'true'
    steps:
      - name: Debug Outputs
        run: echo "Server Changes ${{ needs.check-changes.outputs }}"
      - name: Nice working
        run: echo "Server Changes Detected"
